# values.yaml
namespace: group2-h
replicaCount: 1
services:
  comment:
    name: comment-service
    image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2/shareidea:commentservicev4
    port: 8084
    env:
      SPRING_DATASOURCE_URL: "jdbc:mysql://g2-rds.cjas2m28ehia.ap-northeast-3.rds.amazonaws.com:3306/ShareIdea?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Password123"
      SERVER_PORT: "8084"
  idea:
    name: idea-service
    image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2/shareidea:ideaservicev4
    port: 8083
    env:
      SPRING_DATASOURCE_URL: "jdbc:mysql://g2-rds.cjas2m28ehia.ap-northeast-3.rds.amazonaws.com:3306/ShareIdea?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Password123"
      SERVER_PORT: "8083"
  userprofile:
    name: userprofile-service
    image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2-user-eks-cp:user
    port: 8082
    env:
      SPRING_DATASOURCE_URL: "jdbc:mysql://g2-rds.cjas2m28ehia.ap-northeast-3.rds.amazonaws.com:3306/ShareIdea?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Password123"
      SERVER_PORT: "8082"
  message:
    name: message-service
    image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2/shareidea:messageservicev4
    port: 8085
    env:
      SPRING_DATASOURCE_URL: "jdbc:mysql://g2-rds.cjas2m28ehia.ap-northeast-3.rds.amazonaws.com:3306/ShareIdea?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Password123"
      SERVER_PORT: "8085"
