# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: LoadBalancer